### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Lukelluke** [ttslr/python-MCD#1]
I find this tool from MCD (by matt), could u please teach us how to use ur tool . Does it used by command line? And how to write the correct command line? It would be nice if u give an example for reference~

**Comment by ttslr** [comment]
Thank you for your attention!

Actually, you need first create a file that stores your waveform data list according to your own test data (like "**wavlist.txt**" or "**uttlist.txt**").
then you can use the **MCD-DTW.py** to calculate the MCD value.

Sorry for the inconvenience.
Good luck！

**Comment by Lukelluke** [comment]
您好，前辈，不知道中文您是否能看懂hhh
我是这样做的，不知道操作姿势对不对：
1.在u t t li

**Comment by Lukelluke** [comment]
您好前辈！不知道中文提问您是否能接受hhh
我现在是这样做的，不知道姿势正不正确：
1.在uttlist.txt 中，填写一个30.wav，以及我自己转换出来的一个文件 parallel1.wav，这两行文件名组成 uttlist.txt 内容。
2.在GT文件夹中，放入两个生成文件（GT我理解为Generate）。
3.在baseline文件夹中，放入两组文件（30.wav和30_gen.wav）（parallel1.wav 和 parallel1_gen.wav）。
Q1：在baseline文件夹中，这两对wav文件我不知道应该怎么设置，目前我的做法是：每一对文件都是 同一个source 语音（未经过处理的）的复制，即（30.wav == 30_gen.wav），以“自身和自身的比较”来作为 baseline，不知道这么理解对不对；如果不正确应该怎么修改才合适？
Q2:在没有加入我的文件之前，用您的30.wav测试，算出来的mcd值为2.5+，真的很低（查阅资料知道说，mcd在4～8之间就算很厉害了）,所以不知道是不是我的操作姿势不正确所致。
Q3:我的source语音sr为22050，我转换出来的语音采用了16000，为了能够配合代码使用，我手动用Audition将采样率提高了，但是却一直报错：
`Processing ----------------- parallel1.wav
/Users/huangshengjie/Desktop/python-MCD-master/MCD-DTW.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sr, x = wavfile.read(filename)
Traceback (most recent call last):
  File "/Users/huangshengjie/Desktop/python-MCD-master/MCD-DTW.py", line 61, in <module>
    mgc1 = readmgc(filename1)
  File "/Users/huangshengjie/Desktop/python-MCD-master/MCD-DTW.py", line 12, in readmgc
    sr, x = wavfile.read(filename)
  File "/Users/huangshengjie/opt/anaconda3/envs/py36/lib/python3.6/site-packages/scipy/io/wavfile.py", line 289, in read
    raise ValueError("Incomplete wav chunk.")
ValueError: Incomplete wav chunk.`
不知道说我应该怎么操作才能正确转换采样率，以符合代码对采样率的需求

以上，谢谢前辈，请前辈指点迷津～

**Comment by ttslr** [comment]
Sorry for the inconvenience.
I already updated the code and maybe you can try it.
I think it's more friendly now. :)

**Comment by Lukelluke** [comment]
Thank u verrrrrry much!
I find another implement about using mcd tool, `https://github.com/SamuelBroughton/Mel-Cepstral-Distortion`
There are  no more 'ValueError: Incomplete wav chunk'  problem. Maybe it can be useful to u too.
 
 I read ur new code again. The problem that i met before seems to be caused by line14 `sr, x = wavfile.read(filename)`
The problem can be recurrent by adjust all the .wav files to another sample rate,(e.g change sr fo converted wav from 16k to 22050; or source from 22050 to 16k).
I just try ur new code ,this problem still exit .
I search for solution for line14, and tried other ways to load .wav, have no use and result in more problems.

Whether u ever meet this problem when u have different sample rate wavs?
And,I'm not sure whether the way that the link implement takes is correct or not . 
![image](https://user-images.githubusercontent.com/10866914/80910939-8e7d2180-8d65-11ea-9c89-2a63c65818d7.png)

**Comment by ttslr** [comment]
I don't know why you have such files have different sample rate.
I think you should keep all waveform files at the same sample rate :)
It's more reasonable.  :)

**Comment by Lukelluke** [comment]
I agree with you, the reason why i have different sr files id that , the authority source wavs ' sr are all 22050. And my converted wavs are generated at default sr 16k. When realized this situation, i choose the simple way to change 16k via audition to 22050 directly, and then countered our embarrassed situation. hhhhhhh
